ggchallengejoao:
  outputs:
    dev:
      dataset: getgroundjoao
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: dynamic-point-367801
      threads: 4
      type: bigquery
  target: dev