
version: 2

models:
  - name: stg_referrals
    description: "Stage table of referrals seed, created to convert timestamp columns"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: company_id
        description: "Id of the referred companies"
      - name: partner_id
        description: "Id of the partner that referred the company"
      - name: consultant_id
        description: "Id of the consultant that worked with the partner"
      - name: status
        description: "Status of the referral"
        tests:
          - accepted_values:
              values: ['disinterested', 'pending', 'successful']
      - name: is_outbound
        description: "is_outboungitd is true when we refer a customer to a partner"
        tests:
          - accepted_values:
              values: [0,1]
              quote: false
      - name: referral_created_at_timestamp
        description: "Creation date of referral converted to timestamp type"
      - name: referral_updated_at_timestamp
        description: "Shows when the status went from `pending` to either `disinterested` or `successful converted to timestamp type"

seeds:
  - name: referrals
    description: "Stage table of referrals seed, created to convert timestamp columns"
    columns:
      - name: id
        description: "The primary key for this table"
      - name: created_at
        description: "Creation date of referral"
      - name: updated_at
        description: "Shows when the status went from `pending` to either `disinterested` or `successful`"
      - name: company_id
        description: "Id of the referred companies"
      - name: partner_id
        description: "Id of the partner that referred the company"
      - name: consultant_id
        description: "Id of the consultant that worked with the partner"
      - name: status
        description: "Status of the referral"
      - name: is_outbound
        description: "is_outbound is true when we refer a customer to a partner"